service: app

frameworkVersion: '3'

provider:
  name: aws
  # for Klayers to worl select appropriate region ant Python runtime
  runtime: python3.8
  region: us-east-1
  stage: dev
  timeout: 10
  memorySize: 128
  layers:
  - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-Pillow:5
  environment:
    THUMBNAIL_SIZE: 128
    #assign self (yaml block), provider: region = eu-west-1
    REGION_NAME: ${self:provider.region}

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:*'

custom:
  bucket: valdas-thumbnails
  pythonRequirements:
    dockerizePip: True
    

functions:
  s3_thumbnail_generator:
    handler: handler.s3_thumbnail_generator
    events:
      - s3:
         bucket: ${self:custom.bucket}
         event: s3:ObjectCreated:*
         rules:
           - suffix: .png

# prior to this run: sls plugin install -n serverless-python-requirements
plugins:
  - serverless-python-requirements
  